In [1]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('./covid_toy.csv')
df.head(7)

,age,gender,fever,cough,city,has_covid
0,60,Male,103.0,Mild,Kolkata,No
1,27,Male,100.0,Mild,Delhi,Yes
2,42,Male,101.0,Mild,Delhi,No
3,31,Female,98.0,Mild,Kolkata,No
4,65,Female,101.0,Mild,Mumbai,No
5,84,Female,NaN,Mild,Bangalore,Yes
6,14,Male,101.0,Strong,Bangalore,No


In [4]:
df["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

in machine learning, all input features are called X and the target/predictedoutput feature is called y. So we will split our data into X and y. We will use train_test_split function from sklearn to split our data into training and testing sets.

In [8]:
X = df.drop(columns="has_covid")
y = df["has_covid"]

In [9]:
X.head()

,age,gender,fever,cough,city
0,60,Male,103.0,Mild,Kolkata
1,27,Male,100.0,Mild,Delhi
2,42,Male,101.0,Mild,Delhi
3,31,Female,98.0,Mild,Kolkata
4,65,Female,101.0,Mild,Mumbai


In [10]:
y.head()

0     No
1    Yes
2     No
3     No
4     No
Name: has_covid, dtype: str

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [12]:
X_train.shape

(80, 5)

In [13]:
X_test.shape

(20, 5)

## without column transformer
Manual approach to transform the data. need to concat all the transformed columns together at the end

In [14]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [15]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [22]:
# adding simple imputer to ferver col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[["fever"]])

X_test_fever = si.transform(X_test[["fever"]])

In [23]:
X_train_fever.shape

(80, 1)

In [24]:
oe = OrdinalEncoder(categories=[["Mild","Strong"]])
X_train_cough = oe.fit_transform(X_train[["cough"]])
X_test_cough = oe.fit_transform(X_test[["cough"]])

X_train_cough.shape

(80, 1)

In [25]:
X_test_cough

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [28]:
ohe=OneHotEncoder(drop="first",sparse_output=False)
X_train_gender_city=ohe.fit_transform(X_train[["gender","city"]])
X_test_gender_city=ohe.transform(X_test[["gender","city"]])

X_train_gender_city.shape



(80, 4)

In [29]:
X_train_gender_city

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],


In [30]:
# so we trasformed all except the age column, we can concatenate all the transformed columns together
# but first we need to seperate age column from X_train and X_test
X_train_age=X_train.drop(columns=["gender","city","fever","cough"]).values
X_test_age=X_test.drop(columns=["gender","city","fever","cough"]).values

X_train_age.shape

(80, 1)

In [31]:
X_train_age

array([[81],
       [ 5],
       [19],
       [27],
       [73],
       [70],
       [49],
       [51],
       [64],
       [83],
       [65],
       [18],
       [16],
       [16],
       [27],
       [84],
       [51],
       [69],
       [82],
       [69],
       [44],
       [74],
       [20],
       [12],
       [33],
       [42],
       [65],
       [23],
       [56],
       [64],
       [13],
       [31],
       [40],
       [49],
       [19],
       [11],
       [14],
       [42],
       [38],
       [46],
       [71],
       [10],
       [60],
       [22],
       [19],
       [65],
       [19],
       [54],
       [81],
       [20],
       [48],
       [82],
       [23],
       [66],
       [ 5],
       [49],
       [ 5],
       [34],
       [79],
       [ 6],
       [10],
       [69],
       [55],
       [34],
       [27],
       [47],
       [73],
       [42],
       [80],
       [47],
       [38],
       [34],
       [25],
       [24],
       [12],
       [24],
       [75],

In [32]:
X_train_transformed=np.concatenate([X_train_age,X_train_gender_city, X_train_fever,X_train_cough],axis=1)
X_test_transformed=np.concatenate([X_test_age,X_test_gender_city, X_test_fever,X_test_cough],axis=1)

X_train_transformed.shape

(80, 7)

In [33]:
X_train_transformed

array([[ 81.,   0.,   0.,   0.,   1., 101.,   0.],
       [  5.,   0.,   0.,   1.,   0., 100.,   0.],
       [ 19.,   0.,   0.,   1.,   0., 100.,   0.],
       [ 27.,   1.,   1.,   0.,   0., 100.,   0.],
       [ 73.,   0.,   1.,   0.,   0., 103.,   0.],
       [ 70.,   1.,   0.,   1.,   0., 103.,   1.],
       [ 49.,   0.,   1.,   0.,   0., 102.,   0.],
       [ 51.,   0.,   0.,   1.,   0., 101.,   1.],
       [ 64.,   0.,   1.,   0.,   0., 101.,   0.],
       [ 83.,   0.,   0.,   1.,   0., 101.,   0.],
       [ 65.,   0.,   0.,   0.,   1.,  98.,   0.],
       [ 18.,   0.,   0.,   0.,   0., 104.,   0.],
       [ 16.,   0.,   0.,   0.,   0., 103.,   0.],
       [ 16.,   1.,   0.,   1.,   0., 104.,   0.],
       [ 27.,   1.,   0.,   1.,   0., 100.,   0.],
       [ 84.,   0.,   0.,   0.,   0., 101.,   0.],
       [ 51.,   1.,   0.,   1.,   0., 104.,   0.],
       [ 69.,   0.,   0.,   0.,   0., 102.,   0.],
       [ 82.,   0.,   0.,   0.,   0., 102.,   1.],
       [ 69.,   0.,   0.,   1.,

## With column transformer

In [34]:
from sklearn.compose import ColumnTransformer

In [35]:
transformer = ColumnTransformer(
    transformers=[
        ("tnf1", SimpleImputer(), ["fever"]),
        ("tnf2", OrdinalEncoder(categories=[["Mild","Strong"]]), ["cough"]),
        ("tnf3", OneHotEncoder(drop="first",sparse_output=False), ["gender","city"])
    ],
    remainder="passthrough"
)

In [37]:
transformer.fit_transform(X_train).shape

(80, 7)

In [38]:
transformer.fit_transform(X_train)

array([[101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [100.,   0.,   0.,   0.,   1.,   0.,   5.],
       [100.,   0.,   0.,   0.,   1.,   0.,  19.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [102.,   0.,   0.,   1.,   0.,   0.,  49.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [101.,   0.,   0.,   1.,   0.,   0.,  64.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [ 98.,   0.,   0.,   0.,   0.,   1.,  65.],
       [104.,   0.,   0.,   0.,   0.,   0.,  18.],
       [103.,   0.,   0.,   0.,   0.,   0.,  16.],
       [104.,   0.,   1.,   0.,   1.,   0.,  16.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [101.,   0.,   0.,   0.,   0.,   0.,  84.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [102.,   1.,   0.,   0.,   0.,   0.,  82.],
       [103.,   0.,   0.,   0.,

In [36]:
transformer.fit_transform(X_test).shape

(20, 7)