In [1]:
import numpy as np

- NumPy is a python lib
- used for working with arrays
- short for "Numerical Python"
- used for computation & processing of single & multi dimensioanl array of elements
- smaller memory consumption & better runtime behavior.

In [2]:
l = [1, 2, 3, 4, 5]
arr = np.array(l)   
print(arr)

[1 2 3 4 5]


In [3]:
type(arr)

numpy.ndarray

In [4]:
a = np.array([1, 2, 3, 4, 5], dtype=float)

In [5]:
a

array([1., 2., 3., 4., 5.])

In [6]:
a.ndim

1

In [7]:
c = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
c.ndim

2

In [9]:
c = np.array([[[[1, 2, 3], [4, 5, 6],[7,8,9]]]])
print(c)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [10]:
c.ndim

4

In [11]:
c.shape

(1, 1, 3, 3)

In [12]:
c.dtype

dtype('int64')

### Accessing/changing specific elements, rows & columns

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
a[0][1]=200

In [16]:
a

array([[  1, 200,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14]])

### Zeros/Ones Method

In [18]:
z=np.zeros((3,4))

In [19]:
z.dtype

dtype('float64')

In [20]:
one=np.ones((3,4),dtype=int)

In [21]:
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [22]:
np.full((3,4,),60,dtype=float)

array([[60., 60., 60., 60.],
       [60., 60., 60., 60.],
       [60., 60., 60., 60.]])

In [23]:
np.random.rand(3,4)

array([[0.73270248, 0.71037226, 0.90136204, 0.85493909],
       [0.77271249, 0.40086076, 0.02403272, 0.05293037],
       [0.79686043, 0.03938237, 0.83057433, 0.964597  ]])

In [24]:
np.random.randint(10,100,size=(3,4))

array([[89, 71, 15, 90],
       [48, 52, 21, 65],
       [24, 35, 93, 38]], dtype=int32)

In [26]:
# List vs array
height = [5.5, 6.0, 5.8]
weight = [65,50,75]

height_arr=np.array(height)
weight_arr=np.array(weight)

bmi = weight_arr/(height_arr**2)
print(bmi)

[2.14876033 1.38888889 2.2294887 ]
